server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/qr
    username: postgres
    password: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
qr:
  app:
    secret: dHsVxiN128n43JKqW79E
    lifetime: 60000
logging:
  level:
    org:
      springframework:
        security: DEBUG
