server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/qr
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create

#  spring.jpa.properties.hibernate.show_sql=true
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.properties.hibernate.use_sql_comments=true
#  logging.level.org.springframework.security=DEBUG spring.jpa.hibernate.ddl-auto=update
