server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/qr
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
